### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by dougmoscrop** [ncb000gt/node-es#58]
Thoughts on moving towards a promise-based API?

**Comment by brozeph** [comment]
This is a good idea. I'll make note to build a version with Promise support as time allows - in the interim, perhaps a simple [native promise wrapper](https://github.com/brozeph/renege) would help?

**Comment by dougmoscrop** [comment]
I might be able to help with a PR if you're interested? but yeah that's what I'm doing for now.

**Comment by brozeph** [comment]
@dougmoscrop - a PR would be great!

**Comment by brozeph** [comment]
@dougmoscrop - thank you for the clean PR!

I've merged and published your changes in v0.5.x

**Comment by dougmoscrop** [comment]
Sweet, thank you, too!

**Comment by dougmoscrop** [comment]
Closing!
