### ISSUE TITLE
Only half the queries get executed (exactly half)

### ISSUE THREAD

**Issue by mtimofiiv** [ncb000gt/node-es#64]
Hello, I am sending a bulk set of queries via the `multiSearch()` method. But the response does not match what I ask for.

When I do 46 queries, I get back 23. When I do 76, I get back 38. When I do 64, I get 32.

More specifically, I pass in an array with say 76 query objects in it, and I get back an array of 38 properly formatted results. There are no errors anywhere I can see.

I have tried sending with explicitly setting the index and without, and each time I get the same result.

Any idea why this would be happening?

**Comment by brozeph** [comment]
Can you provide a code example?

**Comment by mtimofiiv** [comment]
Certainly! Here's a function that does it:

```js
function runQuerySet(querySet) {
  return new Promise((resolve, reject) => {
    es.multiSearch({}, querySet, (err, bulkResultSet) => {
      if (err) return reject(err)

      /*
        Some logic here with processing the results, but for brevity's sake
        we will just return the counts cause that's why we're here...
      */

      return resolve({
        queryLength: querySet.length,
        resultLength: bulkResultSet.responses.length
      })
    })
  })
}

runQuerySet(queries).then(result => {
  console.log(result) // ends up being { queryLength: 4, resultLength: 2 }
})
```

Here are 2 sample queries I am getting this with:

```js
[
  { query: { bool: { must: [ { match: { name: 'create.offer' } } ] } } },
  { query: { bool: { must: [ { match: { name: 'landing' } } ] } } }
]
```

And the result set ends up like this:

```js
{ responses: [ { took: 29, timed_out: false, _shards: [Object], hits: [Object] } ] }
// dummy [Object]s shown, but that is not important
```

The expected response here would be 2 items in the `responses` array, one for each query.

**Comment by mtimofiiv** [comment]
Could this have something to do with the fact that [in the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html), it looks like all their examples of multiget all have a header and in [`core.js`](https://github.com/ncb000gt/node-es/blob/master/lib/core.js#L392) we see this comment where there are only queries?

If half my queries are being interpreted as headers, then that would explain the half result set!

**Comment by brozeph** [comment]
Hi @mtimofiiv - yes, that is correct - there needs to be a "header" prior to each query that includes things like the `index` and `searchType`. 

If the payload example from above is altered to look as follows, does the query result in the correct number of results?

```javascript
[
  { },
  { query: { bool: { must: [ { match: { name: 'create.offer' } } ] } } },
  { },
  { query: { bool: { must: [ { match: { name: 'landing' } } ] } } }
]
```

**Comment by mtimofiiv** [comment]
Ok cool. Would it be nice then to note this in the docs for future users? I can submit a PR to specify this in the readme.

**Comment by brozeph** [comment]
@mtimofiiv - sorry for taking so long to respond... a PR would be awesome!

**Comment by brozeph** [comment]
Closing for now... no modifications were added to the documentation, but a a really great plan would be to update links in the readme to the elastic.co docs for each function.
